on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad
        id: build
        continue-on-error: true

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Check build status
        if: steps.build.outcome == 'failure'
        run: exit 1

      - name: publish-package
        uses: atopile/publish-package@v1.1.2
        with:
          # Either: derive the version from a config file (e.g., pyproject.toml or ato.yaml)
          # [Recommended and default if neither are provided]
          ato-config: "ato.yaml"
          # Or: Specify the atopile version directly
          atopile-version: "0.4.1"

          # Version of the package to publish. If empty, the version is expected in the ato.yaml file.
          package-version: "from-tag"

          # Skip publishing if the version already exists. If "false", the action will fail if the version already exists.
          # This is useful if you want to publish from the `main` branch or whenever the `package.version` is bumped.
          skip-duplicate-versions: "true"

          # A path (`path/to/package`) to the package to publish.
          # Useful for monorepos where you have more than one package, or the atopile project isn't the root of the repo.
          package-entrypoint: "./"
